name: automl_dependencies
dependencies:
  - python=2.7.13
  - pandas==0.20.3
  - Flask==0.11.1
  - pytest==2.9.2
  - numpy==1.13.1
  - scikit-learn==0.19.0
  - Werkzeug==0.12.2
  - PyYAML==3.12
  - pip:
      - Flask_RESTful==0.3.6
      - gunicorn==19.7.1
      - requests==2.18.3
      - TPOT==0.8.3
      - tsfresh==0.9.0
